### ISSUE TITLE
MSVC Visual Studio 16 2019 compile error

### ISSUE THREAD

**Issue by jahnf** [eyalz800/zpp_bits#105]
Hi and thank you for publishing this very nice library. I tried to switch from zpp serializer to zpp::bits with a cross platform C++20 project, and I got a weird compiler error with my github actions with Visual Studio 16 2019. (I have not yet tried with newer MSVC compiler versions)

`zpp_bits.h(885,1): fatal error C1004: unexpected end-of-file found`

**Do you have any idea how to get `Visual Studio 16 2019` to compile zpp_bits?**

Github action: relevant OS and compiler config: (gcc, and clang works)
```yaml
          - os: windows-2019
            generator: "Visual Studio 16 2019"
            compiler: msvc
            build_type: Release```
```

Detected compiler (CMake):
```
-- The CXX compiler identification is MSVC 19.29.30147.0
-- The C compiler identification is MSVC 19.29.30147.0
```

Error message:
```txt
...
  tcp-connection.cc
D:/a/server/server/third-party/zpp_bits\zpp_bits/zpp_bits.h(885,1): fatal error C1004: unexpected end-of-file found [D:\a\server\server\build\utils\tcp\utils_tcp.vcxproj]
```
